name: do illegal things

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - 'main'pull_request

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
